#!/usr/bin/env python3
"""Cancellation-safe directional ingredients for a second Green response.

For the scaled momentum map

    G(theta, w) = (theta - r, r),
    r = mu * w + eta * grad F(theta),

the nonlinear defect generated by a displacement ``z=(dtheta,dw)`` is

    N(z) = (-eta * R, eta * R),
    R = grad F(theta+dtheta) - grad F(theta) - Hess F(theta)dtheta.

Directly forming ``R`` is numerically useless for the tiny post-recentering
responses in the Transformer records.  The exact integral identity

    R = int_0^1 (1-t) D^3 F(theta+t*dtheta)[dtheta,dtheta] dt

avoids subtraction of nearly equal optimizer maps.  The quadrature routines
below are diagnostics in ordinary floating point; a proof-producing caller
must add a verified quadrature/arithmetic remainder to Theorem 1's
``sigma_q`` interface.
"""

from __future__ import annotations

from collections.abc import Callable

import numpy as np
import torch
from torch import Tensor

from transformer_hvp_grokking import (
    TransformerConfig,
    gradient,
    objective,
    objective_hvp,
)


def third_gradient_contraction(
    scalar_objective: Callable[[Tensor], Tensor],
    point: Tensor,
    direction: Tensor,
) -> Tensor:
    """Return ``D^3 scalar_objective(point)[direction,direction,.]``.

    Reverse-over-reverse-over-reverse differentiation evaluates the
    directional contraction without differencing two gradients or HVPs.
    """

    if point.shape != direction.shape:
        raise ValueError("point and direction must have identical shape")
    if point.ndim != 1:
        raise ValueError("point and direction must be flat vectors")
    fixed_direction = direction.detach()
    if not bool(torch.any(fixed_direction != 0.0)):
        return torch.zeros_like(point)
    with torch.enable_grad():
        variable = point.detach().requires_grad_(True)
        value = scalar_objective(variable)
        (gradient,) = torch.autograd.grad(value, variable, create_graph=True)
        (hessian_direction,) = torch.autograd.grad(
            torch.dot(gradient, fixed_direction),
            variable,
            create_graph=True,
        )
        (third_direction,) = torch.autograd.grad(
            torch.dot(hessian_direction, fixed_direction),
            variable,
        )
    return third_direction.detach()


def transformer_objective_third_direction(
    parameter: Tensor,
    direction: Tensor,
    train_pairs: Tensor,
    train_labels: Tensor,
    template,
    spec,
    config: TransformerConfig,
) -> Tensor:
    """Third objective derivative contracted twice with ``direction``."""

    return third_gradient_contraction(
        lambda value: objective(
            value,
            train_pairs,
            train_labels,
            template,
            spec,
            config,
        ),
        parameter,
        direction,
    )


def optimizer_nonlinear_defect_quadrature(
    parameter: Tensor,
    scaled_state_direction: Tensor,
    train_pairs: Tensor,
    train_labels: Tensor,
    template,
    spec,
    config: TransformerConfig,
    *,
    nodes: int = 2,
) -> Tensor:
    """Approximate the exact signed nonlinear optimizer defect stably.

    Gauss--Legendre quadrature is applied to the exact integral expression.
    ``nodes=1`` is *not* the center quadratic term because its node is 1/2;
    use :func:`optimizer_center_quadratic_defect` for that diagnostic.
    """

    if scaled_state_direction.ndim != 1 or scaled_state_direction.numel() != 2 * parameter.numel():
        raise ValueError("scaled_state_direction has the wrong shape")
    if nodes < 1:
        raise ValueError("nodes must be positive")
    parameter_direction = scaled_state_direction[: parameter.numel()].detach()
    if not bool(torch.any(parameter_direction != 0.0)):
        return torch.zeros_like(scaled_state_direction)
    abscissae, weights = np.polynomial.legendre.leggauss(nodes)
    accumulated = torch.zeros_like(parameter)
    for abscissa, weight in zip(abscissae, weights):
        time = 0.5 * (float(abscissa) + 1.0)
        interval_weight = 0.5 * float(weight)
        shifted = parameter + time * parameter_direction
        third = transformer_objective_third_direction(
            shifted,
            parameter_direction,
            train_pairs,
            train_labels,
            template,
            spec,
            config,
        )
        accumulated = accumulated + interval_weight * (1.0 - time) * third
    scaled_velocity_remainder = config.learning_rate * accumulated
    return torch.cat((-scaled_velocity_remainder, scaled_velocity_remainder))


def optimizer_center_quadratic_defect(
    parameter: Tensor,
    scaled_state_direction: Tensor,
    train_pairs: Tensor,
    train_labels: Tensor,
    template,
    spec,
    config: TransformerConfig,
) -> Tensor:
    """Return the second-order center term ``D^2G[z,z]/2``."""

    if scaled_state_direction.ndim != 1 or scaled_state_direction.numel() != 2 * parameter.numel():
        raise ValueError("scaled_state_direction has the wrong shape")
    parameter_direction = scaled_state_direction[: parameter.numel()].detach()
    third = transformer_objective_third_direction(
        parameter,
        parameter_direction,
        train_pairs,
        train_labels,
        template,
        spec,
        config,
    )
    scaled_velocity_remainder = 0.5 * config.learning_rate * third
    return torch.cat((-scaled_velocity_remainder, scaled_velocity_remainder))


def optimizer_amplified_secant_defect(
    parameter: Tensor,
    scaled_state_direction: Tensor,
    train_pairs: Tensor,
    train_labels: Tensor,
    template,
    spec,
    config: TransformerConfig,
    *,
    amplification: float,
    base_gradient: Tensor | None = None,
) -> Tensor:
    """Approximate the exact nonlinear defect with an amplified secant.

    For ``a = scaled_state_direction[:d]`` this evaluates

        eta / lambda^2 * (
            grad F(theta + lambda*a) - grad F(theta) - lambda*H(theta)a
        )

    and returns the corresponding ``(-r, r)`` scaled-momentum forcing.
    The signal inside parentheses grows quadratically in ``lambda``.  If
    ``D^4 F`` is bounded by ``L4`` on the radial segment, the exact optimizer
    defect at ``a`` differs from this secant by at most

        sqrt(2) * eta * abs(lambda - 1) * L4 * ||a||^3 / 6.

    A proof-producing caller must additionally enclose arithmetic error in the
    gradient and HVP evaluations.  Supplying a previously computed
    ``base_gradient`` avoids one redundant reverse pass.
    """

    if scaled_state_direction.ndim != 1 or scaled_state_direction.numel() != 2 * parameter.numel():
        raise ValueError("scaled_state_direction has the wrong shape")
    lam = float(amplification)
    if not np.isfinite(lam) or lam <= 0.0:
        raise ValueError("amplification must be finite and positive")
    parameter_direction = scaled_state_direction[: parameter.numel()].detach()
    if not bool(torch.any(parameter_direction != 0.0)):
        return torch.zeros_like(scaled_state_direction)
    if base_gradient is None:
        base_gradient = gradient(
            parameter,
            train_pairs,
            train_labels,
            template,
            spec,
            config,
        )
    elif base_gradient.shape != parameter.shape:
        raise ValueError("base_gradient has the wrong shape")
    shifted_gradient = gradient(
        parameter + lam * parameter_direction,
        train_pairs,
        train_labels,
        template,
        spec,
        config,
    )
    linear = objective_hvp(
        parameter,
        parameter_direction,
        train_pairs,
        train_labels,
        template,
        spec,
        config,
    )
    gradient_remainder = (
        shifted_gradient - base_gradient - lam * linear
    ) / (lam * lam)
    scaled_velocity_remainder = config.learning_rate * gradient_remainder
    return torch.cat((-scaled_velocity_remainder, scaled_velocity_remainder))
